### ISSUE TITLE
Failure when doing domain pdf

### ISSUE THREAD

**Issue by akc42** [akc42/AKCMoney#104]
```
money:pdfdomain Rollback error ReferenceError: __dirname is not defined
    at codeHeader (file:///app/server/pdf/domain.js:76:20)
    at file:///app/server/pdf/domain.js:199:9
    at sqliteTransaction (/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.default [as domain] (file:///app/server/pdf/domain.js:267:7)
    at file:///app/server/server.js:521:22
    at Layer.handle [as handle_request] (/app/node_modules/router/lib/layer.js:93:5)
    at next (/app/node_modules/router/lib/route.js:161:13)
    at Route.dispatch (/app/node_modules/router/lib/route.js:121:3)
    at handle (/app/node_modules/router/index.js:532:11)
    at Layer.handle [as handle_request] (/app/node_modules/router/lib/layer.js:93:5) +9ms
```

**Comment by akc42** [comment]
Same problem in account pdf - its related to using  "`__dirname, <directory>`,  in path.resolve which is no longer valid instead use 
`new URL(<directory>, import.meta.url).pathname`
