### ISSUE TITLE
I was reconcilling credit card and this occured.  

### ISSUE THREAD

**Issue by akc42** [akc42/AKCMoney#74]
```
Error: Cannot read property 'name' of undefined : TypeError: Cannot read property 'name' of undefined
0|money-ap | 2021-05-06 16:46:44:     at /home/alan/money/server/api/account.js:68:39
0|money-ap | 2021-05-06 16:46:44:     at sqliteTransaction (/home/alan/money/node_modules/better-sqlite3/lib/transaction.js:58:24)
0|money-ap | 2021-05-06 16:46:44:     at Object.module.exports [as account] (/home/alan/money/server/api/account.js:122:7)
0|money-ap | 2021-05-06 16:46:44:     at /home/alan/money/server/server.js:386:26
0|money-ap | 2021-05-06 16:46:44:     at Layer.handle [as handle_request] (/home/alan/money/node_modules/router/lib/layer.js:93:5)
0|money-ap | 2021-05-06 16:46:44:     at next (/home/alan/money/node_modules/router/lib/route.js:144:13)
0|money-ap | 2021-05-06 16:46:44:     at Route.dispatch (/home/alan/money/node_modules/router/lib/route.js:109:3)
0|money-ap | 2021-05-06 16:46:44:     at handle (/home/alan/money/node_modules/router/index.js:526:11)
0|money-ap | 2021-05-06 16:46:44:     at Layer.handle [as handle_request] (/home/alan/money/node_modules/router/lib/layer.js:93:5)
0|money-ap | 2021-05-06 16:46:44:     at /home/alan/money/node_modules/router/index.js:296:22 
0|money-ap | 2021-05-06 16:46:44: with request url of  /api//account
```

The reconcilled balance had not been updated, although all the transactions had been cleared.  I got an error saying that someone else had updated the same account in parallel

**Comment by akc42** [comment]
Although I have not fixed anything, the code has changed and it seems pointless keeping this issue open as an examination of the actual error doesn't make sense
